### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'members')

### ISSUE THREAD

**Issue by daviddarkins-accenture** [keirbowden/LDNSCALL2020SF#1]
Hello im getting the following error....running 4.0.5, any help would be greatly appreciated

Documenting Org
An error occurred documenting the org - TypeError: Cannot set properties of undefined (setting 'members')
Stack trace:
TypeError: Cannot set properties of undefined (setting 'members')
    at ObjectProcessor.expandGroups (.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/object/objects.js:151:23)
    at ObjectProcessor.process (.local/share/sfdx/node_modules/bbdoc/lib/shared/processors/object/objects.js:38:14)
    at Documentor.process (.local/share/sfdx/node_modules/bbdoc/lib/shared/documentor.js:55:32)
    at Documentor.document (.local/share/sfdx/node_modules/bbdoc/lib/shared/documentor.js:38:22)
    at Doc.run (.local/share/sfdx/node_modules/bbdoc/lib/commands/bbdoc/doc.js:56:24)
    at async Doc._run (.local/share/sfdx/node_modules/bbdoc/node_modules/@salesforce/command/lib/sfdxCommand.js:91:40)
    at async Config.runCommand (.local/share/sfdx/client/7.151.1-cd9fb0c/node_modules/@oclif/config/lib/config.js:173:24)
    at async SfdxMain.run (.local/share/sfdx/client/7.151.1-cd9fb0c/node_modules/@oclif/command/lib/main.js:27:9)
    at async SfdxMain._run (.local/share/sfdx/client/7.151.1-cd9fb0c/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (.local/share/sfdx/client/7.151.1-cd9fb0c/dist/cli.js:162:47)

My the objects potion of the Project looks like   

"objects": {
    "name": "objects",
    "description": "All Objects",
    "backgroundColor": "#ff8b00",
    "color": "#ffffff",
    "subdirectory": "objects",
    "reportDirectory": "objs",
    "image": "images/objects.png",
    "suffix": "object",
    "groups": {
      "Standard": {
        "name": "Standard",
        "title": "Standard Objects",
        "backgroundColor": "#c9a9d6",
        "color": "#01010c",
        "columns": [
          "Name",
          "Label",
          "Type",
          "Description",
          "Info",
          "Page Layouts",
          "Security",
          "Compliance",
          "In Use",
          "Encrypted"
        ],
        "description": "Standard Salesforce Objects",
        "objects": "Account, AccountContactRelation, Activity, Case, CaseMilestone, Entitlement, Event, User, Lead"
      },
      "Other": {
        "name": "other",
        "columns": [
          "Name",
          "Label",
          "Type",
          "Description",
          "Info",
          "Page Layouts",
          "Security",
          "Compliance",
          "In Use",
          "Encrypted"
        ],
        "title": "Uncategorised Objects",
        "description": "Objects that do not fall into any other category"
      }
    }
  }

**Comment by daviddarkins-accenture** [comment]
I think I have resolved this.....I removed the standard Flow block (below, from the sample config file) from the config file and it started generating the file again. Happy to share any more info if it helps

    "flows": {
        "name": "flows",
        "description": "Flows providing automation", 
        "image": "images/flows.jpg",
        "subdirectory": "flows",
        "suffix":"flow",
        "groups": {
            "other": {
                "name":"other", 
                "title":"All Flows",
                "description": "All flows defined in the example repo"
            }
        }
    },
